export const AUDIT_ACTIONS = [
  // Auth
  "login_failed",
  "login_succeeded",
  "pin_changed",
  "sessions_revoked",
  "actor_selected",
  // Registrations
  "registration_approved",
  "registration_rejected",
  "registration_bulk_approved",
  "registration_bulk_rejected",
  "registration_status_changed",
  "registration_edited",
  // REG-6: approved by pointing at a member who was already on the roll, so the
  // trail shows the request did not create anyone.
  "registration_linked_to_member",
  // Members
  "member_created",
  "member_updated",
  "member_deactivated",
  "member_reactivated",
  "members_imported",
  "batch_created",
  "batch_deleted",
  // Attendance
  "session_created",
  "session_deleted",
  "attendance_changed",
  "attendance_roster_replaced",
  // Appeals
  "appeal_approved",
  "appeal_rejected",
  "appeals_approved_all",
  "appeal_auto_approved",
  // Reports
  "report_generated",
  "report_approved",
  "report_rejected",
  "report_archived",
  "report_downloaded",
  // Liturgy
  "liturgy_saved",
  "liturgy_template_saved",
  "liturgy_template_deleted",
  // Comms
  "announcement_created",
  "announcement_deleted",
  // Payments
  "structure_created",
  "structure_updated",
  "payment_recorded",
  "payment_voided",
  // Settings
  "settings_updated",
  "backup_downloaded",
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];

export const AUDIT_ACTION_LABELS: Record<AuditAction, string> = {
  login_failed: "Login failed",
  login_succeeded: "Login succeeded",
  pin_changed: "PIN changed",
  sessions_revoked: "Sessions revoked",
  actor_selected: "Actor selected",
  registration_approved: "Registration approved",
  registration_rejected: "Registration rejected",
  registration_bulk_approved: "Registrations approved in bulk",
  registration_bulk_rejected: "Registrations rejected in bulk",
  registration_status_changed: "Registration status changed",
  registration_edited: "Registration edited",
  registration_linked_to_member: "Registration linked to an existing member",
  member_created: "Member created",
  member_updated: "Member updated",
  member_deactivated: "Member deactivated",
  member_reactivated: "Member reactivated",
  members_imported: "Members imported",
  batch_created: "Batch created",
  batch_deleted: "Batch deleted",
  session_created: "Session created",
  session_deleted: "Session deleted",
  attendance_changed: "Attendance changed",
  attendance_roster_replaced: "Attendance roster replaced",
  appeal_approved: "Appeal approved",
  appeal_rejected: "Appeal rejected",
  appeals_approved_all: "All appeals approved",
  appeal_auto_approved: "Appeal auto-approved",
  report_generated: "Report generated",
  report_approved: "Report approved",
  report_rejected: "Report rejected",
  report_archived: "Report archived",
  report_downloaded: "Report downloaded",
  liturgy_saved: "Liturgy saved",
  liturgy_template_saved: "Liturgy template saved",
  liturgy_template_deleted: "Liturgy template deleted",
  announcement_created: "Announcement created",
  announcement_deleted: "Announcement deleted",
  structure_created: "Payment structure created",
  structure_updated: "Payment structure updated",
  payment_recorded: "Payment recorded",
  payment_voided: "Payment voided",
  settings_updated: "Settings updated",
  backup_downloaded: "Backup downloaded",
};
